name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install --no-install-recommends -y gcc-aarch64-linux-gnu flex bison device-tree-compiler bc libssl-dev build-essential curl git gnat libncurses5-dev locales m4 zlib1g-dev u-boot-tools file wget cpio unzip rsync

      - name: Build Buildroot
        run: |
         export BUILDROOT_DEFCONFIG=cortex-a75_defconfig
         ./build_buildroot.sh $BUILDROOT_DEFCONFIG

      - name: Build Linux
        run: |
         export DTS=a75.dts
         ./build_linux_payload.sh $DTS

      - name: Build Coreboot
        run: |
         export GIC_VERSION=3
         ./build_coreboot_with_linux.sh $GIC_VERSION

      - name: Prepare artifacts
        run: |
         export FILE_SUFFIX=armv8_2a-gicv3
         mkdir -p artifacts
         cp coreboot/build/bl31.elf artifacts/bl31-atf-$FILE_SUFFIX.elf
         cp coreboot/build/coreboot.rom artifacts/coreboot-linux-$FILE_SUFFIX.rom
         cp linux/vmlinux artifacts/vmlinux-$FILE_SUFFIX
         cp linux_files/virt.dtb artifacts/virt-$FILE_SUFFIX.dtb
         cp linux_files/Image artifacts/Image-$FILE_SUFFIX
         cp linux_files/rootfs.cpio artifacts/rootfs-$FILE_SUFFIX.cpio

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts/

